backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "bio"
    label: "Bio"
    files:
      - name: "bio_content"
        label: "Bio Content"
        file: "_data/bio.yml"
        fields:
          - { label: "Bio Image", name: "image", widget: "image", required: true }
          - { label: "Bio Text", name: "text", widget: "markdown", required: true }
  - name: "shows"
    label: "Shows"
    folder: "_shows"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Town", name: "town", widget: "string", required: true }
      - { label: "Venue", name: "venue", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime", required: true }
      - { label: "Supporting Acts", name: "support", widget: "string", required: false }
      - { label: "Ticket Link", name: "ticket_link", widget: "string", required: false }
  - name: "music_projects"
    label: "Music Projects"
    folder: "_music_projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Category", name: "category", widget: "select", options: ["Solo Work", "Bands & Projects", "Ensembles"], required: true }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Order", name: "order", widget: "number", required: false }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - { label: "Link Text", name: "text", widget: "string" }
          - { label: "URL", name: "url", widget: "string" }
      - { label: "Cover Image", name: "cover_image", widget: "image", required: false }
      - { label: "Active", name: "active", widget: "boolean", default: true }